### ISSUE TITLE
Participation

### ISSUE THREAD

**Issue by skandragon** [7u83/actube#10]
I'm somewhat interested in replacing the (ancient) Cisco 4402 I have acquired with something modern.  I have 1252 LWAPs, but would like to also eventually be able to turn any OpenWRT (or derived) AP into an LWAP.

I am new to all this terminology, but I am very interested in what I can and can't do with these APs, if I were to help on the controller software.  From my read, you are basically re-implementing what Cisco calls the "WLC" in software.  Is this right?

I'm happy to start helping with functionality, but my time is somewhat limited.  I'm wanting to stop using a totally outdated bit of equipment though, and would very much like to move into the world where I can pick up an OpenWRT compatible AP from Fry's and drop it in place as part of a manageable group.

Is there a list of what works, what doesn't, what's urgent, what isn't?  I've cloned the source, but have not yet gotten to compiling.  That's next!

**Comment by skandragon** [comment]
BTW, I am especially interested in supporting modern features like 802.11k, which I think will be a major win.  I'm also quite keen on supporting some more advanced remote monitoring (rogue detection as well as a general purpose wifi sniffer) if the hardware supports this.  I know the Cisco CleanAir stuff is probably out of reach, but at least sniffing some channel on some (perhaps otherwise unused) AP would be nice, and then being able to turn it back into an AP later.

**Comment by alagoutte** [comment]
Hi,

The project is experimental for the moment... 
the idea is to have the AC (Access Controler) working to replace WLC or other stuff...

**Comment by skandragon** [comment]
I get that.  :)

I have a Cisco 4400 here at home, and would very much like to stop using it at some point in the not too distant future.

I'm a coder, and more than happy to help, but I might need a little advice on what features are most important first.  I would very much like to have my existing Cisco AP 1252s be able to do fancy new stuff like 802.11k, which isn't new other than the 4400 I have won't do it.  I think this is needed to increase stability of apple products, among others.

So, where would I start, and is it at least stable enough that it will work?  I'm still setting up a small "lab" sort of config here, and I have a mirror port on my switch that I can use to monitor what the APs and Cisco controller talk about.

**Comment by skandragon** [comment]
BTW, I read on your blog that you installed the Cisco virtual WLC on VirtualBox.  What host OS did you use?  I tried MacOS, and I was unable to convince APs to connect to it.  I did not try flashing them from their 7.0.x firmware, as I expected them to flash up once they associate.

**Comment by skandragon** [comment]
I've installed ubuntu 14.04 on an older mac-mini, and when one of my access points attempts to connect, I get this:

```
DBG: Info - Starting wtpman in non-dtls mode
DBG: Pkt IN - From 10.53.0.10 l=123:  H:4 R:00 W:01 Flgs:(M) Frag/Offs:0/0 R-MAC:00:17:df:ab:fc:00
    00 20 02 10 00 00 00 00 06 00 17 DF AB FC 00 00 00 00 00 01 00 00 66 00 00 14 00 01 00 00 27 00  | . ....................f.......'.
    28 02 02 00 01 00 40 96 00 00 00 00 04 01 00 00 00 00 40 96 00 00 01 00 04 07 00 FC 00 00 40 96  | (.....@...........@...........@.
    00 00 02 00 04 0C 04 0A 00 00 29 00 01 04 00 2C 00 01 01 00 25 00 0A 00 40 96 00 00 CF 03 01 00  | ..........)....,....%...@.......
    01 00 25 00 16 00 40 96 00 00 05 41 50 30 30 31 65 2E 66 37 31 61 2E 64 32 39 65  | ..%...@....AP001e.f71a.d29e
DBG: Msg IN - Discovery Request Message (type=1) from 10.53.0.10 , Seqnum: 0 ElemLen: 99
DBG: Msg Element - 20 (Discovery Type), len=1
    00  | .
DBG: Msg Element - 39 (WTP Descriptor), len=40
    02 02 00 01 00 40 96 00 00 00 00 04 01 00 00 00 00 40 96 00 00 01 00 04 07 00 FC 00 00 40 96 00  | .....@...........@...........@..
    00 02 00 04 0C 04 0A 00  | ........
DBG: Elem Error - Bad WTP Descriptor, number of encryption elements is 0.
DBG: Msg Element - 41 (WTP Frame Tunnel Mode), len=1
    04  | .
DBG: Msg Element - 44 (WTP MAC Type), len=1
    01  | .
DBG: Msg Element - 37 (Vendor Specific Payload/Cisco/207 - WTP Board Data Options), len=10
    00 40 96 00 00 CF 03 01 00 01  | .@........
DBG: Warning -  Can't handle Vendor Specific Payload Cisco/207, in msg 1 (Discovery Request) in Discovery state.
DBG: Msg Element - 37 (Vendor Specific Payload/Cisco/5 - RAD Name), len=22
    00 40 96 00 00 05 41 50 30 30 31 65 2E 66 37 31 61 2E 64 32 39 65  | .@....AP001e.f71a.d29e
DBG: Warning -  Can't handle Vendor Specific Payload Cisco/5, in msg 1 (Discovery Request) in Discovery state.
DBG: Msg Error - Missing mandatory elements: [WTP Board Data, WTP Descriptor]
DBG: Msg Error - Ignoring Discovery Request from 10.53.0.10 - missing mandatory elements.
```

**Comment by alagoutte** [comment]
Hi Michael,

Do you have "enable the Cisco CAPWAP mode ? because Cisco AP need some "Cisco Vendor Stuff" to work (in this case RAD Name)

And also like it is say, it is very experimental... not all stuff working !

**Comment by skandragon** [comment]
I know it's experimental.  I'm not expecting a finished product, I'm expecting that I will need to help with development to get it working :)
